version: "3.7"
services:

  app: 
    container_name: acal-app
    image: alexandrequeiroz/app:1.0.1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - acal-network

  api:
    container_name: acal-api
    image: alexandrequeiroz/api:1.0.1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:${MYSQLDB_PORT}/acaldb
      - SPRING_DATASOURCE_USERNAME=${MYSQLDB_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}  
      - SERVER_PORT=${SPRING_PORT}
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:${SPRING_PORT}/health/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
    networks:
      - acal-network

  db:
    container_name: acal-db
    image: mysql:8.0-debian
    restart: always
    environment:
      MYSQL_DATABASE: acaldb
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "${MYSQLDB_PORT}:${MYSQLDB_PORT}"
    volumes:
      - /var/mysql/acal:/var/lib/mysql
    networks:
      - acal-network

networks:
  acal-network:
    driver: bridge
